language: php
php:
  - 5.6
matrix:
  allow_failures:
    - php: hhvm
    - php: php-fpm
  fast_finish: true
env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
    - TEST_BASEDIR=.modman/ApiPlus/dev/tests/apiplus
  matrix:
    - MAGENTO_VERSION=CE-1.9.2.4
services:
  - mysql
mysql:
  database: magento
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

script:
  - bash ./setup/install.sh
notifications:
  email:
    recipients:
      - tiago@tiagosampaio.com
    on_success: always
    on_failure: always
