sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - php-fpm
matrix:
  includes:
    - php: 5.3
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.4
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.5
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.5
      env: WP_TRAVISCI=travis:phpunit
    - php: hhvm
      env: WP_TRAVISCI=travis:phpunit
    - php: php-fpm
      env: WP_TRAVISCI=travis:phpunit
  allow_failures:
    - php: hhvm
    - php: php-fpm
  fast_finish: true
notifications:
  email:
    recipients:
      - tiago@tiagosampaio.com
    on_success: always
    on_failure: always
