sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - php-fpm
matrix:
  allow_failures:
    - php: hhvm
    - php: php-fpm
notifications:
  email:
    recipients:
      - tiago@tiagosampaio.com
    on_success: always
    on_failure: always
