language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 5.3
    - php: 7.0
  fast_finish: true
  
env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
    - TEST_BASEDIR=.modman/ApiPlus/dev/tests/apiplus
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.4
    - MAGENTO_VERSION=magento-mirror-1.9.2.3
    - MAGENTO_VERSION=magento-mirror-1.9.2.2
    - MAGENTO_VERSION=magento-mirror-1.9.2.1
    - MAGENTO_VERSION=magento-mirror-1.9.2.0
    - MAGENTO_VERSION=magento-mirror-1.9.1.1
    - MAGENTO_VERSION=magento-mirror-1.9.1.0
    - MAGENTO_VERSION=magento-mirror-1.9.0.1
    - MAGENTO_VERSION=magento-mirror-1.9.0.0
    - MAGENTO_VERSION=magento-mirror-1.8.1.0
    - MAGENTO_VERSION=magento-mirror-1.8.0.0
    - MAGENTO_VERSION=magento-mirror-1.7.0.2

mysql:
  database: magento
  username: root
  encoding: utf8

script:
  - bash ./setup/run.sh
  
notifications:
  email:
    recipients:
      - tiago@tiagosampaio.com
    on_success: always
    on_failure: always
