sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - php-fpm
matrix:
  allow_failures:
    - php: hhvm
    - php: php-fpm
  fast_finish: true
env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
    - TEST_BASEDIR=.modman/ApiPlus/dev/tests/apiplus
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.4
    - MAGENTO_VERSION=magento-mirror-1.9.2.2
    - MAGENTO_VERSION=magento-mirror-1.9.1.1
    - MAGENTO_VERSION=magento-mirror-1.9.0.1
    - MAGENTO_VERSION=magento-mirror-1.8.1.0
    - MAGENTO_VERSION=magento-mirror-1.8.0.0
    - MAGENTO_VERSION=magento-mirror-1.7.0.2
script:
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - tiago@tiagosampaio.com
    on_success: always
    on_failure: always
