sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - php-fpm
matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.5
    - php: hhvm
    - php: php-fpm
  allow_failures:
    - php: hhvm
    - php: php-fpm
  fast_finish: true
notifications:
  email:
    recipients:
      - tiago@tiagosampaio.com
    on_success: always
    on_failure: always
