language: php
php:
  - 5.6
matrix:
  allow_failures:
    - php: hhvm
    - php: php-fpm
  fast_finish: true
  
env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
    - TEST_BASEDIR=.modman/ApiPlus/dev/tests/apiplus
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.4
    - MAGENTO_VERSION=magento-mirror-1.9.2.3
    - MAGENTO_VERSION=magento-mirror-1.9.2.2
    - MAGENTO_VERSION=magento-mirror-1.9.2.1

mysql:
  database: magento
  username: root
  encoding: utf8

script:
  - bash ./setup/run.sh
  
notifications:
  email:
    recipients:
      - tiago@tiagosampaio.com
    on_success: always
    on_failure: always
